### ISSUE TITLE
fix: lmdb storage overhead

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp-contracts-lmdb#1]
LMDB seems to have a large storage overhead https://github.com/kriszyp/lmdb-js/issues/194
Also - we're storing old cache entries for contract - which should be pruned - https://github.com/warp-contracts/warp/issues/244
\- but as the issue in the lmdb-js suggests - it might not recover too much space.

If that will be the case - we will need to periodically "rewrite" the database to a new one, with only few last cache entries (i.e. with `highest` sortKeys) for each contract.

**Comment by ppedziwiatr** [comment]
another thing - the default page size of the lmdb seems to be 16384, not 4096 - https://github.com/kriszyp/lmdb-js/issues/202

**Comment by janekolszak** [comment]
https://github.com/warp-contracts/warp-contracts-lmdb/pull/2
